# -*- coding: utf-8 -*-
"""Классификатор слов.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHA0jv8nWWMoc6eP6GllvLGlYNvucJ3H
"""

from transformers import Trainer
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments
from transformers import EarlyStoppingCallback
from datasets import load_dataset
import torch.nn as nn
import numpy as np
from sklearn.model_selection import StratifiedKFold
import matplotlib.pyplot as plt
from transformers import Trainer
from copy import deepcopy
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import torch
from datasets import Dataset

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        outputs = model(**inputs)
        logits = outputs.logits
        labels = inputs.get("labels")

        # --- Замените здесь loss на свою ---
        # Пример 1: взвешенная кросс-энтропия
        class_weights = torch.tensor([0.27, 0.73]).to(logits.device)  # веса для классов 0 и 1
        loss_fn = nn.CrossEntropyLoss()
        loss = loss_fn(logits, labels)

        return (loss, outputs) if return_outputs else loss

dataset = load_dataset(
    "csv",
    data_files={
        "train": "datasets/dataset_multi_augmented.csv",
    }
)

# оставляем только нужные столбцы
dataset = dataset.remove_columns(
    [c for c in dataset["train"].column_names if c not in ["word",
    "protolanguage", "borrowed_century"]]
)

dataset = dataset.rename_column("protolanguage", "label")

def replace_protoslavic(example):
    if example["label"] == "Proto-Slavic":
        example["label"] = "INHERITED"
    return example

def to_labels(example):
  if example["label"] == 'INHERITED':
    example["label"] = 0
  else:
    example["label"] = 1
  return example

dataset = dataset.map(replace_protoslavic)
dataset = dataset.map(to_labels)

model_name = "DeepPavlov/rubert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(
        batch["word"],
        padding="max_length",
        truncation=True,
        max_length=16,  # для слов достаточно
    )

dataset = dataset.map(tokenize, batched=True)
dataset = dataset.rename_column("label", "labels")
dataset.set_format("torch")

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

training_args = TrainingArguments(
    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=64,

    num_train_epochs=8,   # важно: данных мало
    weight_decay=0.01,

    logging_steps=10,
    load_best_model_at_end=True,

    report_to="none",
    optim="adamw_torch" # Explicitly set a non-fused optimizer
)

fold_histories = []

# splited = dataset["train"].train_test_split(test_size=0.2)

# train_dataset = splited["train"]
# eval_dataset = splited["test"]

labels = np.array(dataset["train"]["labels"])
centuries = np.array(dataset["train"]["borrowed_century"])

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="binary"
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

all_f1 = []

for fold, (train_idx, val_idx) in enumerate(skf.split(np.zeros(len(labels)), labels)):

    print(f"\n===== Fold {fold+1} =====")

    train_dataset = dataset["train"].select(train_idx)
    val_dataset = dataset["train"].select(val_idx)

    train_dataset = train_dataset.remove_columns(["word", "borrowed_century"])
    val_dataset = val_dataset.remove_columns(["word", "borrowed_century"])

    # создаём НОВУЮ модель каждый раз
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=2
    )

    trainer = WeightedTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        #callbacks=[EarlyStoppingCallback(early_stopping_patience=8)],
    )

    trainer.train()

    # собираем F1 по эпохам
    history = trainer.state.log_history

    epochs = []
    f1_scores = []

    for record in history:
        if "eval_f1" in record:
            epochs.append(record["epoch"])
            f1_scores.append(record["eval_f1"])

    fold_histories.append((epochs, f1_scores))

    metrics = trainer.evaluate()

    fold_f1 = metrics["eval_f1"]
    print("Fold F1:", fold_f1)

    all_f1.append(fold_f1)

    #test_words_english = ["застёжка", "книга", "стек", "файтинг"]
    #test_words_french = ["застёжка", "книга", "фужер", "манеж"]
    #test_words_german = ["застёжка", "книга", "цейтнот", "галстук"]
    #test_words_japanese = ["застёжка", "книга", "гайдзин", "маття"]
    #test_words_multi = ["дом","книга","естество","любить","смотреть", "держать", "жертва", "лукошко", "простак",#простые наследованные слова
        #"стек","файтинг","фужер","манеж","цейтнот","галстук","гайдзин","маття",#простые заимствованные слова
        #"дебажить","электричество","тональность","штуковина",#заимствования с русскими суффиксами и окончаниями
        #"зацепинг", #наследованное слово с заимствованным окончанием
        #"надлом","строительство","щекотка","зачитать","подорожник","опровержение","оценка"]#наследованные слова со сложным словообразованием

    #test_words_multi_epochs = [
        #"штурм", "бухгалтер", "балет", "экипаж", "яхта", "митинг", "кимоно", "самурай",#Заимствования 18 века (кроме японских. До второй половиный 19 века такого пласта заимствований не существовало)
        #"вуаль", "режиссёр", "цейхгауз", "ландшафт", "футбол", "ростбиф", "банзай", "гейша",#Заимствования 19 века
        #"компьютер", "бизнесмен", "сервант", "пюре", "шахта", "дуршлаг", "каратэ", "суши"#Заимствования 20 века
    #]

    #all_test_words = [
        #test_words_multi,
        #test_words_multi_epochs,
    #]

    #testset = list(set().union(*all_test_words))

    #Устанавливаем тестовые датасеты, чтобы проверить, насколько хорошо модель определяет конкретные заимствования
    arabian_testset = load_dataset('csv', data_files='datasets/dataset_arabian.csv')['train']
    chinese_testset = load_dataset('csv', data_files='datasets/dataset_chinese.csv')['train']
    english_testset = load_dataset('csv', data_files='datasets/dataset_english.csv')['train']
    french_testset = load_dataset('csv', data_files='datasets/dataset_french.csv')['train']
    german_testset = load_dataset('csv', data_files='datasets/dataset_german.csv')['train']
    italian_testset = load_dataset('csv', data_files='datasets/dataset_italian.csv')['train']
    japanese_testset = load_dataset('csv', data_files='datasets/dataset_japanese.csv')['train']
    polish_testset = load_dataset('csv', data_files='datasets/dataset_polish.csv')['train']

    # токенизация
    def tokenize(batch):
        return tokenizer(
            batch["word"],
            padding="max_length",
            truncation=True,
            max_length=16,
        )

    arabian_testset = arabian_testset.map(tokenize, batched=True)
    arabian_testset.set_format("torch")
    arabian_testset = arabian_testset.remove_columns(['word',"Unnamed: 0"])
    arabian_testset = arabian_testset.rename_column('protolanguage','label')
    arabian_testset = arabian_testset.map(replace_protoslavic)
    arabian_testset = arabian_testset.map(to_labels)

    chinese_testset = chinese_testset.map(tokenize, batched=True)
    chinese_testset.set_format("torch")
    chinese_testset = chinese_testset.remove_columns(["word","Unnamed: 0"])
    chinese_testset = chinese_testset.rename_column('protolanguage','label')
    chinese_testset = chinese_testset.map(replace_protoslavic)
    chinese_testset = chinese_testset.map(to_labels)

    english_testset = english_testset.map(tokenize, batched=True)
    english_testset.set_format("torch")
    english_testset = english_testset.remove_columns(['word', "Unnamed: 0"])
    english_testset = english_testset.rename_column('protolanguage','label')
    english_testset = english_testset.map(replace_protoslavic)
    english_testset = english_testset.map(to_labels)

    french_testset = french_testset.map(tokenize, batched=True)
    french_testset.set_format("torch")
    french_testset = french_testset.remove_columns(['word',"Unnamed: 0"])
    french_testset = french_testset.rename_column('protolanguage','label')
    french_testset = french_testset.map(replace_protoslavic)
    french_testset = french_testset.map(to_labels)

    german_testset = german_testset.map(tokenize, batched=True)
    german_testset.set_format("torch")
    german_testset = german_testset.remove_columns(['word',"Unnamed: 0"])
    german_testset = german_testset.rename_column('protolanguage','label')
    german_testset = german_testset.map(replace_protoslavic)
    german_testset = german_testset.map(to_labels)

    italian_testset = italian_testset.map(tokenize, batched=True)
    italian_testset.set_format("torch")
    italian_testset = italian_testset.remove_columns(['word',"Unnamed: 0"])
    italian_testset = italian_testset.rename_column('protolanguage','label')
    italian_testset = italian_testset.map(replace_protoslavic)
    italian_testset = italian_testset.map(to_labels)

    japanese_testset = japanese_testset.map(tokenize, batched=True)
    japanese_testset.set_format("torch")
    japanese_testset = japanese_testset.remove_columns(['word',"Unnamed: 0"])
    japanese_testset = japanese_testset.rename_column('protolanguage','label')
    japanese_testset = japanese_testset.map(replace_protoslavic)
    japanese_testset = japanese_testset.map(to_labels)

    polish_testset = polish_testset.map(tokenize, batched=True)
    polish_testset.set_format("torch")
    polish_testset = polish_testset.remove_columns(['word',"Unnamed: 0"])
    polish_testset = polish_testset.rename_column('protolanguage','label')
    polish_testset = polish_testset.map(replace_protoslavic)
    polish_testset = polish_testset.map(to_labels)

    # предсказания
    predictions_arabian = trainer.predict(arabian_testset)
    predictions_chinese = trainer.predict(chinese_testset)
    predictions_english = trainer.predict(english_testset)
    predictions_french = trainer.predict(french_testset)
    predictions_german = trainer.predict(german_testset)
    predictions_italian = trainer.predict(italian_testset)
    predictions_japanese = trainer.predict(japanese_testset)
    predictions_polish = trainer.predict(polish_testset)

    print("Точность определения арабских заимств.:", compute_metrics((predictions_arabian.predictions,predictions_arabian.label_ids)))
    print("Точность определения китайских заимств.:", compute_metrics((predictions_chinese.predictions,predictions_chinese.label_ids)))
    print("Точность определения английских заимств.:", compute_metrics((predictions_english.predictions,predictions_english.label_ids)))
    print("Точность определения французских заимств.:", compute_metrics((predictions_french.predictions,predictions_french.label_ids)))
    print("Точность определения немецких заимств.:", compute_metrics((predictions_german.predictions,predictions_german.label_ids)))
    print("Точность определения итальянских заимтсв.:", compute_metrics((predictions_italian.predictions,predictions_italian.label_ids)))
    print("Точность определения японских заимств.:", compute_metrics((predictions_japanese.predictions,predictions_japanese.label_ids)))
    print("Точность определения польских заимств.:", compute_metrics((predictions_polish.predictions,predictions_polish.label_ids)))

    # логиты → вероятности
    #probs = torch.nn.functional.softmax(
    #    torch.tensor(predictions.predictions), dim=1
    #)

    #predicted_labels = torch.argmax(probs, dim=1)

    #for word, label, prob in zip(testset, predicted_labels, probs):
        #print(f"{word} → класс {label.item()} (уверенность {prob[label].item():.3f})")

    #print(trainer.evaluate())

print("\n===== FINAL RESULT =====")
print("Mean F1:", np.mean(all_f1))
print("Std F1:", np.std(all_f1))

plt.figure()

for i, (epochs, f1_scores) in enumerate(fold_histories):
    plt.plot(epochs, f1_scores, label=f"Блок {i+1}")

plt.xlabel("Итерация")
plt.ylabel("Метрика F1")
plt.title("Метрика F1 за итерацию по каждому блоку")
plt.legend()

plt.savefig("plots/bert_epochs.png")

plt.show()
