# -*- coding: utf-8 -*-
"""Классификация слов (ByT5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeGudWmcVyGranfAg5CPPVP5vq06VCB4
"""

from datasets import load_dataset
from transformers import Trainer
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments
import torch.nn as nn
import numpy as np
from sklearn.model_selection import StratifiedKFold
import matplotlib.pyplot as plt
from transformers import Trainer
from copy import deepcopy
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import torch
from datasets import Dataset
import random as rd

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        outputs = model(**inputs)
        logits = outputs.logits
        labels = inputs.get("labels")

        # --- Замените здесь loss на свою ---
        # Пример 1: взвешенная кросс-энтропия
        class_weights = torch.tensor([0.27, 0.73]).to(logits.device)  # веса для классов 0 и 1
        loss_fn = nn.CrossEntropyLoss()
        loss = loss_fn(logits, labels)

        return (loss, outputs) if return_outputs else loss

dataset = load_dataset(
    "csv",
    data_files={
        "train": "datasets/dataset_multi_augmented.csv",
    }
)

declinable = dataset["train"].filter(lambda x: x["declinable"] == True)
undeclinable = dataset["train"].filter(lambda x: x["declinable"] == False)

declinable = rd.sample(list(declinable["word"]), 5)
undeclinable = rd.sample(list(undeclinable["word"]), 5)

words = declinable + undeclinable

#Заимствованные корни с наследованными приставками и суффиксами. Необходимо рассмотреть внимание для этих слов
test_words = ["дебажить", "электричество", "тональность", "штуковина", "сервак", "акк", "агриться", "залутать", "видос", "криповый", "имба"]

# оставляем только нужные столбцы
dataset = dataset.remove_columns(
    [c for c in dataset["train"].column_names if c not in ["word",
    "protolanguage"]]
)

dataset = dataset.rename_column("protolanguage", "label")

def replace_protoslavic(example):
    if example["label"] == "Proto-Slavic":
        example["label"] = "INHERITED"
    return example

def to_labels(example):
  if example["label"] == 'INHERITED':
    example["label"] = 0
  else:
    example["label"] = 1
  return example

dataset = dataset.map(replace_protoslavic)
dataset = dataset.map(to_labels)

from transformers import AutoTokenizer
from transformers import DataCollatorForSeq2Seq

tokenizer = AutoTokenizer.from_pretrained("/userspace/kad2/byt5")

def tokenize(batch):
    #texts = ["etymology: " + w for w in batch["word"]]
    return tokenizer(
        batch["word"],
        padding="max_length",
        truncation=True,
        max_length=16,  # для слов достаточно
        return_tensors="pt",
    )

dataset = dataset.map(tokenize, batched=True)
dataset = dataset.rename_column("label", "labels")
dataset.set_format("torch")

labels = np.array(dataset['train']['labels'])

from transformers import T5ForSequenceClassification

model = T5ForSequenceClassification.from_pretrained("/userspace/kad2/byt5", num_labels=2)

# data_collator = DataCollatorForSeq2Seq(
#     tokenizer,
#     model=model,
#     padding=True
# )

from transformers import TrainingArguments, T5ForSequenceClassification, EarlyStoppingCallback

training_args = TrainingArguments(
    output_dir="./byt5-etymology",
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,

    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=64,

    num_train_epochs=100,
    weight_decay=0.01,

    logging_steps=10,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",    # или "accuracy" и т.п.
    greater_is_better=False,              # или True для accuracy

    report_to="none",
    optim="adamw_torch" # Explicitly set a non-fused optimizer
)

from sklearn.model_selection import StratifiedKFold
import matplotlib.pyplot as plt

fold_histories = []

# splited = dataset["train"].train_test_split(test_size=0.2)

# train_dataset = splited["train"]
# eval_dataset = splited["test"]

labels = np.array(dataset["train"]["labels"])
#century = np.array(dataset["train"]["borrowed_century"])

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

from transformers import Trainer, DataCollatorWithPadding
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    # Иногда logits приходит как tuple (logits, ...)
    if isinstance(logits, tuple):
        logits = logits[0]

    preds = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="binary",
        zero_division=0
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

all_f1 = []
general_correct_predictions = []

for fold, (train_idx, val_idx) in enumerate(skf.split(np.zeros(len(labels)), labels)):
    # создаём НОВУЮ модель каждый раз
    model = T5ForSequenceClassification.from_pretrained("/userspace/kad2/byt5",
                                                        num_labels=2,
                                                        attn_implementation="eager")
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    plt.figure(figsize=(30,30))
    # 2. токенизация
    inputs = tokenizer(
        words,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    # 3. перенос на GPU
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # 4. forward pass (ВАЖНО: return_dict=True)
    outputs = model(
        **inputs,
        output_attentions=True,
        return_dict=True
    )

    # 5. берём encoder attention (а не outputs.attentions!)
    attentions = outputs.encoder_attentions

    # 6. выбираем слой и голову
    layer = -1
    head = 0

    for i, w in enumerate(words):
        attn = attentions[layer][i].mean(dim=0).detach().cpu().numpy()

        plt.subplot(5, 2, i+1)
        # 7. токены (байтовые)
        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][i])

        # 8. визуализация
        plt.imshow(attn, interpolation="nearest")
        plt.xticks(range(len(tokens)), tokens, rotation=90)
        plt.yticks(range(len(tokens)), tokens)
        plt.title(f"ByT5 encoder attention for word {words[i]}")
        plt.colorbar()

    # 9. сохранение (не забудь создать папку заранее)
    import os
    os.makedirs("./etymology-analysis", exist_ok=True)

    plt.savefig(f"./etymology-analysis/ByT5_attention_pretrained{fold}.png")
    plt.show()


    plt.figure(figsize=(30,30))
    num_heads = attentions[layer].shape[1]
    for h in range(num_heads):
        attn = attentions[layer][0, h].detach().cpu().numpy()

        plt.subplot(3, 4, h+1)
        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

        plt.imshow(attn, interpolation="nearest")
        plt.xticks(range(len(tokens)), tokens, rotation=90)
        plt.yticks(range(len(tokens)), tokens)
        plt.title(f"ByT5 attn: word - {words[0]}, head - {h}")
        plt.colorbar()

    plt.savefig(f"./etymology-analysis/ByT5_attention_pretrained_all_heads{fold}.png")



    plt.figure(figsize=(30,30))
    # 2. токенизация
    inputs = tokenizer(
        test_words,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    # 3. перенос на GPU
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # 4. forward pass (ВАЖНО: return_dict=True)
    outputs = model(
        **inputs,
        output_attentions=True,
        return_dict=True
    )

    # 5. берём encoder attention (а не outputs.attentions!)
    attentions = outputs.encoder_attentions

    for i, w in enumerate(test_words):
        attn = attentions[layer][i].mean(dim=0).detach().cpu().numpy()

        plt.subplot(6, 2, i+1)
        # 7. токены (байтовые)
        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][i])

        # 8. визуализация
        plt.imshow(attn, interpolation="nearest")
        plt.xticks(range(len(tokens)), tokens, rotation=90)
        plt.yticks(range(len(tokens)), tokens)
        plt.title(f"ByT5 encoder attention for word {test_words[i]}")
        plt.colorbar()

    plt.tight_layout()
    plt.savefig(f"./etymology-analysis/ByT5_attention_pretrained_{fold}.png")


    print(f"\n===== Fold {fold+1} =====")

    train_dataset = dataset["train"].select(train_idx)
    val_dataset = dataset["train"].select(val_idx)

    train_dataset = train_dataset.remove_columns(['word'])
    val_dataset = val_dataset.remove_columns(['word'])

    trainer = WeightedTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=10)],
    )

    trainer.train()

    # собираем F1 по эпохам
    history = trainer.state.log_history
    
    epochs = []
    f1_scores = []

    print(history)

    for record in history:
        if "eval_f1" in record:
            epochs.append(record["epoch"])
            f1_scores.append(record["eval_f1"])

    fold_histories.append((epochs, f1_scores))

    metrics = trainer.evaluate()

    fold_f1 = metrics["eval_f1"]
    print("Fold F1:", fold_f1)

    all_f1.append(fold_f1)

    #test_words_english = ["застёжка", "книга", "стек", "файтинг"]
    #test_words_french = ["застёжка", "книга", "фужер", "манеж"]
    #test_words_german = ["застёжка", "книга", "цейтнот", "галстук"]
    #test_words_japanese = ["застёжка", "книга", "гайдзин", "маття"]
    #test_words_multi = ["дом","книга","естество","любить","смотреть", "держать", "жертва", "лукошко", "простак",#простые наследованные слова
        #"стек","файтинг","фужер","манеж","цейтнот","галстук","гайдзин","маття",#простые заимствованные слова
        #"дебажить","электричество","тональность","штуковина",#заимствования с русскими суффиксами и окончаниями
        #"зацепинг", #наследованное слово с заимствованным окончанием
        #"надлом","строительство","щекотка","зачитать","подорожник","опровержение","оценка"]#наследованные слова со сложным словообразованием

    #test_words_multi_epochs = [
        #"штурм", "бухгалтер", "балет", "экипаж", "яхта", "митинг", "кимоно", "самурай",#Заимствования 18 века (кроме японских. До второй половиный 19 века такого пласта заимствований не существовало)
        #"вуаль", "режиссёр", "цейхгауз", "ландшафт", "футбол", "ростбиф", "банзай", "гейша",#Заимствования 19 века
        #"компьютер", "бизнесмен", "сервант", "пюре", "шахта", "дуршлаг", "каратэ", "суши"#Заимствования 20 века
    #]

    #all_test_words = [
       # test_words_multi,
        #test_words_multi_epochs,
    #]

    #testset = list(set().union(*all_test_words))

    #Устанавливаем тестовые датасеты, чтобы проверить, насколько хорошо модель определяет конкретные заимствования
    arabian_testset = load_dataset('csv', data_files='datasets/dataset_arabian.csv')['train']
    chinese_testset = load_dataset('csv', data_files='datasets/dataset_chinese.csv')['train']
    english_testset = load_dataset('csv', data_files='datasets/dataset_english.csv')['train']
    french_testset = load_dataset('csv', data_files='datasets/dataset_french.csv')['train']
    german_testset = load_dataset('csv', data_files='datasets/dataset_german.csv')['train']
    italian_testset = load_dataset('csv', data_files='datasets/dataset_italian.csv')['train']
    japanese_testset = load_dataset('csv', data_files='datasets/dataset_japanese.csv')['train']
    polish_testset = load_dataset('csv', data_files='datasets/dataset_polish.csv')['train']

    # токенизация
    def tokenize(batch):
        return tokenizer(
            batch["word"],
            padding="max_length",
            truncation=True,
            max_length=16,
        )

    arabian_testset = arabian_testset.map(tokenize, batched=True)
    arabian_testset.set_format("torch")
    arabian_testset = arabian_testset.remove_columns(['word',"Unnamed: 0"])
    arabian_testset = arabian_testset.rename_column('protolanguage','label')
    arabian_testset = arabian_testset.map(replace_protoslavic)
    arabian_testset = arabian_testset.map(to_labels)

    chinese_testset = chinese_testset.map(tokenize, batched=True)
    chinese_testset.set_format("torch")
    chinese_testset = chinese_testset.remove_columns(["word","Unnamed: 0"])
    chinese_testset = chinese_testset.rename_column('protolanguage','label')
    chinese_testset = chinese_testset.map(replace_protoslavic)
    chinese_testset = chinese_testset.map(to_labels)

    english_testset = english_testset.map(tokenize, batched=True)
    english_testset.set_format("torch")
    english_testset = english_testset.remove_columns(['word', "Unnamed: 0"])
    english_testset = english_testset.rename_column('protolanguage','label')
    english_testset = english_testset.map(replace_protoslavic)
    english_testset = english_testset.map(to_labels)

    french_testset = french_testset.map(tokenize, batched=True)
    french_testset.set_format("torch")
    french_testset = french_testset.remove_columns(['word',"Unnamed: 0"])
    french_testset = french_testset.rename_column('protolanguage','label')
    french_testset = french_testset.map(replace_protoslavic)
    french_testset = french_testset.map(to_labels)

    german_testset = german_testset.map(tokenize, batched=True)
    german_testset.set_format("torch")
    german_testset = german_testset.remove_columns(['word',"Unnamed: 0"])
    german_testset = german_testset.rename_column('protolanguage','label')
    german_testset = german_testset.map(replace_protoslavic)
    german_testset = german_testset.map(to_labels)

    italian_testset = italian_testset.map(tokenize, batched=True)
    italian_testset.set_format("torch")
    italian_testset = italian_testset.remove_columns(['word',"Unnamed: 0"])
    italian_testset = italian_testset.rename_column('protolanguage','label')
    italian_testset = italian_testset.map(replace_protoslavic)
    italian_testset = italian_testset.map(to_labels)

    japanese_testset = japanese_testset.map(tokenize, batched=True)
    japanese_testset.set_format("torch")
    japanese_testset = japanese_testset.remove_columns(['word',"Unnamed: 0"])
    japanese_testset = japanese_testset.rename_column('protolanguage','label')
    japanese_testset = japanese_testset.map(replace_protoslavic)
    japanese_testset = japanese_testset.map(to_labels)

    polish_testset = polish_testset.map(tokenize, batched=True)
    polish_testset.set_format("torch")
    polish_testset = polish_testset.remove_columns(['word',"Unnamed: 0"])
    polish_testset = polish_testset.rename_column('protolanguage','label')
    polish_testset = polish_testset.map(replace_protoslavic)
    polish_testset = polish_testset.map(to_labels)

    # предсказания
    predictions_arabian = trainer.predict(arabian_testset)
    predictions_chinese = trainer.predict(chinese_testset)
    predictions_english = trainer.predict(english_testset)
    predictions_french = trainer.predict(french_testset)
    predictions_german = trainer.predict(german_testset)
    predictions_italian = trainer.predict(italian_testset)
    predictions_japanese = trainer.predict(japanese_testset)
    predictions_polish = trainer.predict(polish_testset)

    print("Точность определения арабских заимств.:", compute_metrics((predictions_arabian.predictions,predictions_arabian.label_ids)))
    print("Точность определения китайских заимств.:", compute_metrics((predictions_chinese.predictions,predictions_chinese.label_ids)))
    print("Точность определения английских заимств.:", compute_metrics((predictions_english.predictions,predictions_english.label_ids)))
    print("Точность определения французских заимств.:", compute_metrics((predictions_french.predictions,predictions_french.label_ids)))
    print("Точность определения немецких заимств.:", compute_metrics((predictions_german.predictions,predictions_german.label_ids)))
    print("Точность определения итальянских заимтсв.:", compute_metrics((predictions_italian.predictions,predictions_italian.label_ids)))
    print("Точность определения японских заимств.:", compute_metrics((predictions_japanese.predictions,predictions_japanese.label_ids)))
    print("Точность определения польских заимств.:", compute_metrics((predictions_polish.predictions,predictions_polish.label_ids)))

    general_correct_predictions.append(
        (predictions_arabian.predictions[0].argmax(axis=-1) == predictions_arabian.label_ids).sum().item()+
        (predictions_chinese.predictions[0].argmax(axis=-1) == predictions_chinese.label_ids).sum().item()+
        (predictions_english.predictions[0].argmax(axis=-1) == predictions_english.label_ids).sum().item()+
        (predictions_french.predictions[0].argmax(axis=-1) == predictions_french.label_ids).sum().item()+
        (predictions_german.predictions[0].argmax(axis=-1) == predictions_german.label_ids).sum().item()+
        (predictions_italian.predictions[0].argmax(axis=-1) == predictions_italian.label_ids).sum().item()+
        (predictions_japanese.predictions[0].argmax(axis=-1) == predictions_japanese.label_ids).sum().item()+
        (predictions_polish.predictions[0].argmax(axis=-1) == predictions_polish.label_ids).sum().item()
    )

    #import torch
    #from datasets import Dataset

    #test_dataset = Dataset.from_dict({"word": testset})

    #test_dataset = test_dataset.map(tokenize, batched=True)
    #test_dataset.set_format("torch")

    # предсказание
    #predictions = trainer.predict(test_dataset)

    # логиты → вероятности
    #probs = torch.nn.functional.softmax(
    #    torch.tensor(predictions[0][0]), dim=1
    #)

    #predicted_labels = torch.argmax(probs, dim=1)

    #for word, label, prob in zip(testset, predicted_labels, probs):
    #    print(f"{word} → класс {label.item()} (уверенность {prob[label].item():.3f})")

    print(trainer.evaluate())

    # 2. токенизация
    inputs = tokenizer(
        words,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    # 3. перенос на GPU
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # 4. forward pass (ВАЖНО: return_dict=True)
    outputs = model(
        **inputs,
        output_attentions=True,
        return_dict=True
    )

    # 5. берём encoder attention (а не outputs.attentions!)
    attentions = outputs.encoder_attentions

    # 6. выбираем слой и голову
    layer = -1
    head = 0

    plt.figure(figsize=(30,30))
    for i, w in enumerate(words):
        attn = attentions[layer][i].mean(dim=0).detach().cpu().numpy()

        plt.subplot(5, 2, i+1)
        # 7. токены (байтовые)
        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][i])

        # 8. визуализация
        plt.imshow(attn, interpolation="nearest")
        plt.xticks(range(len(tokens)), tokens, rotation=90)
        plt.yticks(range(len(tokens)), tokens)
        plt.title(f"ByT5 encoder attention for word {words[i]}")
        plt.colorbar()

    # 9. сохранение (не забудь создать папку заранее)
    import os
    os.makedirs("./etymology-analysis", exist_ok=True)

    plt.savefig(f"./etymology-analysis/ByT5_attention{fold}.png")
    plt.show()

    plt.figure(figsize=(30,30))
    num_heads = attentions[layer].shape[1]
    for h in range(num_heads):
        attn = attentions[layer][0, h].detach().cpu().numpy()

        plt.subplot(3, 4, h+1)
        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

        plt.imshow(attn, interpolation="nearest")
        plt.xticks(range(len(tokens)), tokens, rotation=90)
        plt.yticks(range(len(tokens)), tokens)
        plt.title(f"ByT5 attn: word - {words[0]}, head - {h}")
        plt.colorbar()

    plt.tight_layout()    
    plt.savefig(f"./etymology-analysis/ByT5_attention_all_heads{fold}.png")

    plt.figure(figsize=(30,30))
    # 2. токенизация
    inputs = tokenizer(
        test_words,
        return_tensors="pt",
        padding=True,
        truncation=True
    )

    # 3. перенос на GPU
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # 4. forward pass (ВАЖНО: return_dict=True)
    outputs = model(
        **inputs,
        output_attentions=True,
        return_dict=True
    )

    # 5. берём encoder attention (а не outputs.attentions!)
    attentions = outputs.encoder_attentions

    for i, w in enumerate(test_words):
        attn = attentions[layer][i].mean(dim=0).detach().cpu().numpy()

        plt.subplot(6, 2, i+1)
        # 7. токены (байтовые)
        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][i])

        # 8. визуализация
        plt.imshow(attn, interpolation="nearest")
        plt.xticks(range(len(tokens)), tokens, rotation=90)

        plt.yticks(range(len(tokens)), tokens)
        plt.title(f"ByT5 encoder attention for word {test_words[i]}")
        plt.colorbar()

    plt.tight_layout()
    plt.savefig(f"./etymology-analysis/ByT5_attention_{fold}.png")

print("\n===== FINAL RESULT =====")
print("Mean F1:", np.mean(all_f1))
print("Std F1:", np.std(all_f1))
print("Total correct predictions per fold:", general_correct_predictions)

plt.figure()

for i, (epochs, f1_scores) in enumerate(fold_histories):
    plt.plot(epochs, f1_scores, label=f"Блок {i+1}")

plt.xlabel("Итерация")
plt.ylabel("Метрика F1")
plt.title("Метрика F1 за итерацию по каждому блоку")
plt.legend()

#plt.savefig("plots/byt5_epochs.png")

plt.show()


